--DROP TABLE IF EXISTS CONTAINER;

CREATE TABLE IF NOT EXISTS CONTAINER (
  containerId VARCHAR(250) PRIMARY KEY,
  lambdaId VARCHAR(250) NOT NULL
);

--DROP TABLE IF EXISTS LAMBDA;

CREATE TABLE IF NOT EXISTS LAMBDA  (
  id VARCHAR(250) PRIMARY KEY,
  containerId VARCHAR(250),
  lastUsedTimestamp bigint
);

--DROP TABLE IF EXISTS JOB;

CREATE TABLE IF NOT EXISTS JOB  (
  id VARCHAR(250) PRIMARY KEY,
  lambdaId VARCHAR(250),
  submitDateTimestamp bigint,
  startDateTimestamp bigint,
  endDateTimestamp bigint,
  status VARCHAR(250),
  result VARCHAR(250)
);